services:
  - type: web
    name: donate-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: thankyou-db
    databaseName: thankyou
    user: postgres
