name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

env:
  APP_NAME: donate-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw clean compile -B

      - name: Run Tests
        run: ./mvnw test -B

      - name: Build JAR
        run: ./mvnw package -DskipTests -B

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1

  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      # Check all required secrets
      - name: Check required secrets
        run: |
          for secret in PRODUCTION_SSH_KEY PRODUCTION_HOST JDBC_DATABASE_URL JDBC_DATABASE_USERNAME JDBC_DATABASE_PASSWORD SLACK_BOT_TOKEN SLACK_SIGNING_SECRET SLACK_APP_TOKEN; do
            if [ -z "${!secret}" ]; then
              echo "❌ $secret is empty or not set"
              exit 1
            else
              echo "✅ $secret is set"
            fi
          done

      - name: Set up SSH key
        run: |
          set -e
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          if [ -z "${{ secrets.PRODUCTION_SSH_KEY }}" ]; then
            echo "ERROR: PRODUCTION_SSH_KEY secret is empty!"
            exit 1
          fi
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_ed25519_root
          chmod 600 ~/.ssh/id_ed25519_root
          if [ ! -s ~/.ssh/id_ed25519_root ]; then
            echo "ERROR: SSH key file is empty!"
            exit 1
          fi
          echo "SSH key file created successfully"
          echo "Key file size: $(wc -c < ~/.ssh/id_ed25519_root) bytes"
          ssh-keygen -l -f ~/.ssh/id_ed25519_root || { echo "ERROR: Invalid SSH key format!"; exit 1; }
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
          echo "SSH setup completed successfully"

      - name: Debug - Check files
        run: |
          echo "Current directory: $(pwd)"
          echo "Target directory contents:"
          ls -la target/
          echo "Dockerfile exists:"
          ls -la Dockerfile || echo "Dockerfile not found"

      - name: Debug - Test SSH connection
        run: |
          set -e
          ssh -vvv -i ~/.ssh/id_ed25519_root -o ConnectTimeout=10 root@${{ secrets.PRODUCTION_HOST }} "echo 'SSH connection successful'" || { echo "SSH connection failed!"; exit 1; }

      - name: Copy files to server
        run: |
          set -e
          echo "Copying JAR file..."
          scp -vvv -i ~/.ssh/id_ed25519_root target/*.jar root@${{ secrets.PRODUCTION_HOST }}:/root/app.jar || { echo "SCP JAR failed!"; exit 1; }
          echo "Copying Dockerfile..."
          scp -vvv -i ~/.ssh/id_ed25519_root Dockerfile root@${{ secrets.PRODUCTION_HOST }}:/root/ || { echo "SCP Dockerfile failed!"; exit 1; }
          echo "Files copied successfully!"

      - name: Deploy using Docker
        run: |
          set -e
          ssh -vvv -i ~/.ssh/id_ed25519_root root@${{ secrets.PRODUCTION_HOST }} '
            set -ex
            cd /root

            docker stop ${{ env.APP_NAME }} 2>/dev/null || true
            docker rm ${{ env.APP_NAME }} 2>/dev/null || true

            docker build -t ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} . || { echo "Docker build failed!"; exit 1; }
            docker tag ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} ${{ env.APP_NAME }}:latest

            docker run -d \
              --name ${{ env.APP_NAME }} \
              --restart unless-stopped \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=production \
              -e JAVA_OPTS="-Xmx1g -Xms512m" \
              -e APP_NAME="${{ secrets.APP_NAME }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e JDBC_DATABASE_URL="${{ secrets.JDBC_DATABASE_URL }}" \
              -e JDBC_DATABASE_USERNAME="${{ secrets.JDBC_DATABASE_USERNAME }}" \
              -e JDBC_DATABASE_PASSWORD="${{ secrets.JDBC_DATABASE_PASSWORD }}" \
              -e SLACK_BOT_TOKEN="${{ secrets.SLACK_BOT_TOKEN }}" \
              -e SLACK_SIGNING_SECRET="${{ secrets.SLACK_SIGNING_SECRET }}" \
              -e SLACK_APP_TOKEN="${{ secrets.SLACK_APP_TOKEN }}" \
              -e SLACK_DONATE_CHANNEL="${{ secrets.SLACK_DONATE_CHANNEL }}" \
              -e SLACK_APP_NAME="${{ secrets.SLACK_APP_NAME }}" \
              -e SECURITY_USERNAME="${{ secrets.SECURITY_USERNAME }}" \
              -e SECURITY_PASSWORD="${{ secrets.SECURITY_PASSWORD }}" \
              ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} || { echo "Docker run failed!"; exit 1; }
            docker image prune -f
          ' || { echo "Remote deploy failed!"; exit 1; }

      - name: Health Check
        run: |
          sleep 30
          curl -f http://${{ secrets.PRODUCTION_HOST }}:8080/actuator/health

      - name: Notify Deployment Success
        if: success()
        run: |
          echo "✅ Production deployment successful!"
          echo "URL: http://${{ secrets.PRODUCTION_HOST }}:8080"

      - name: Notify Deployment Failure
        if: failure()
        run: |
          echo "❌ Production deployment failed!"
