name: Java CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Add permissions to fix resource access issues
permissions:
  contents: read
  actions: read
  security-events: write
  id-token: write

env:
  APP_NAME: donate-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          ./mvnw clean compile -B

      - name: Run Tests
        run: |
          ./mvnw test -B

      - name: Build JAR
        run: |
          ./mvnw package -DskipTests -B

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
          retention-days: 1

  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRODUCTION_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          scp -i ~/.ssh/id_ed25519 target/*.jar root@${{ secrets.PRODUCTION_HOST }}:/root/app.jar
          scp -i ~/.ssh/id_ed25519 Dockerfile root@${{ secrets.PRODUCTION_HOST }}:/root/

      - name: Deploy using Docker
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.PRODUCTION_HOST }} '
            cd /root
            
            docker stop ${{ env.APP_NAME }} 2>/dev/null || true
            docker rm ${{ env.APP_NAME }} 2>/dev/null || true
            
            docker build -t ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .
            docker tag ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} ${{ env.APP_NAME }}:latest
            
            docker run -d \
              --name ${{ env.APP_NAME }} \
              --restart unless-stopped \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=production \
              -e JAVA_OPTS="-Xmx1g -Xms512m" \
              -e APP_NAME="${{ secrets.APP_NAME }}" \
              -e PORT="${{ secrets.PORT }}" \
              -e JDBC_DATABASE_URL="${{ secrets.JDBC_DATABASE_URL }}" \
              -e JDBC_DATABASE_USERNAME="${{ secrets.JDBC_DATABASE_USERNAME }}" \
              -e JDBC_DATABASE_PASSWORD="${{ secrets.JDBC_DATABASE_PASSWORD }}" \
              -e SLACK_BOT_TOKEN="${{ secrets.SLACK_BOT_TOKEN }}" \
              -e SLACK_SIGNING_SECRET="${{ secrets.SLACK_SIGNING_SECRET }}" \
              -e SLACK_APP_TOKEN="${{ secrets.SLACK_APP_TOKEN }}" \
              -e SLACK_DONATE_CHANNEL="${{ secrets.SLACK_DONATE_CHANNEL }}" \
              -e SLACK_APP_NAME="${{ secrets.SLACK_APP_NAME }}" \
              -e SECURITY_USERNAME="${{ secrets.SECURITY_USERNAME }}" \
              -e SECURITY_PASSWORD="${{ secrets.SECURITY_PASSWORD }}" \
              ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
            
            docker image prune -f
          '

      - name: Health Check
        run: |
          sleep 30
          curl -f http://${{ secrets.PRODUCTION_HOST }}:8080/actuator/health

      - name: Notify Deployment Success
        if: success()
        run: |
          echo "✅ Production deployment successful!"
          echo "URL: http://${{ secrets.PRODUCTION_HOST }}:8080"

      - name: Notify Deployment Failure
        if: failure()
        run: |
          echo "❌ Production deployment failed!"
